music_directory         "/root/mmc/mp3" #歌曲目录
playlist_directory      "/root/mmc/mp3/.mpd/" #播放列表存放目录
db_file                 "/root/mmc/mp3/.mpd/mpd.db" #歌曲列表
log_file                "/tmp/mpd.log"
pid_file                "/tmp/mpd.pid"
user                    "root" 
group                   "users"
bind_to_address         "0.0.0.0"
port                    "6600"
audio_output {
     type         "alsa"        
     name         "My ALSA Device"        
     device         "hw:0,0" 
     format         "44100:16:2"
     mixer_control        "PCM"
}
filesystem_charset        "UTF-8"

# id3v1_encoding          "gb2312"

#OSS Mixer
mixer_type "software"
#mixer_device "/dev/mixer"
#mixer_control "speaker"

auto_update "yes"
# gapless_mp3_playback "yes"