      - name: Prepare release artifacts（打包固件 + config.buildinfo）
        if: steps.compile_firm.outputs.result == 'ok'
        run: |
          mkdir -p release_out
          # 全局搜索所有bin/manifest/buildinfo，不限层级，防止路径错位
          find openwrt/bin -type f \( -name "*.bin" -o -name "*.manifest" -o -name "config.buildinfo" \) -exec cp {} release_out/ \;
          echo "release_out目录文件列表："
          ls -la release_out
          # 校验是否存在bin文件，没有直接报错终止后续release
          if [ ! -n "$(ls -A release_out/*.bin 2>/dev/null)" ];then
            echo "::error::release_out内未找到bin固件文件！"
            exit 1
          fi

      - name: 创建Release发布
        if: steps.compile_firm.outputs.result == 'ok'
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.BUILD_TAG }}
          name: build‑rax3000emmc包含passwall ${{ env.BUILD_DATETIME }}
          artifacts: release_out/*
          generateReleaseNotes: true
          allowUpdates: true
          # 增加重要参数，解决tag重复覆盖、附件不上传bug
          draft: false
          prerelease: false
